site_name: IoETPlanet
nav:
  - Home: index.md
  - Raspberry Pi:
      - Installing Docker on Raspberry Pi: raspberrypi/docker-on-raspberrypi.md
  - NVIDIA Jetson Nano:
     - Installing Docker on NVIDIA Jetson: nvidia/docker-on-jetson-nano.md


theme: material
